web:
  build: .
  command: bin/web
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
    - herokuPostgresql
worker:
  build: .
  command: bin/worker
  environment:
    REDIS_URL: 'redis://herokuRedis:6379'
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  links:
    - herokuRedis
    - herokuPostgresql
shell:
  build: .
  command: bash
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuRedis:
  image: redis
herokuPostgresql:
  image: postgres
